### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by NeuroRoboticTech** [davidenunes/tensorflow-wheels#13]
I downloaded your build for TF 2.3 | GPU | python3.8 | cuda11 |cudnn 8 | XLA,SSE4.X,AVX,AVX2,FMA | Arch Linux x86_64 and installed it. However, when I try and import tensorflow I get the following error

`>>> import tensorflow
Traceback (most recent call last):
  File "/home/mfp/virtualenv/py38/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/mfp/virtualenv/py38/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mfp/virtualenv/py38/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/mfp/virtualenv/py38/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/home/mfp/virtualenv/py38/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/home/mfp/virtualenv/py38/lib/python3.8/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/mfp/virtualenv/py38/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/mfp/virtualenv/py38/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/mfp/virtualenv/py38/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
`

I am running on Ubuntu 18.04 LTS with cuda 11 and cuDNN 8 installed. I looked into this error some and the default glibc is 2.27 for Ubuntu 18, and there does not appear to be any simple method of upgrading to 2.29 unless I move to Ubuntu 19 or greater. I cannot do that though. Any ideas on how to fix this, or is there a different package I should be using? Thanks for your help.

**Comment by salomonMuriel** [comment]
Your best bet is downgrading to CUDA 10.2, cudNN 7.6.5, and using the
corresponding wheels.

As you say, there is no easy way to upgrade glibc without breaking your
build and without upgrading to 19.04.

The true best solution is going all the way up to 20.04, but if that's
impossible then downgrading is the next best option.

**Comment by davidenunes** [comment]
Thanks for answering @salomonMuriel, my advice would be the exact same @NeuroRoboticTech. If you can't upgrade I would downgrade CUDA and cuDNN. If there's anything else you need, feel free to open the issue again 👍
